# Generated by Django 3.1.2 on 2020-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20201017_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.FilePathField(path='/media'),
        ),
    ]
