# Generated by Django 3.1.2 on 2020-10-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
